version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tcc-db
    networks:
      - backend-network

  inventory-service:
    build:
        dockerfile: Dockerfile.inventory
    container_name: inventory-service
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - backend-network

  order-service:
    build:
      dockerfile: Dockerfile.order
    container_name: order-service
    ports:
      - "4000:3002"
    depends_on:
      - inventory-service
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge